# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  style-check:
    docker:
      - image: circleci/python:3.7.2

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: style-check
          command: |
            pip install --user -U flake8
            python -m flake8 --show-source signac_dashboard/


  test-3.7: &test-template
    docker:
      - image: circleci/python:3.7.2

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            git submodule update --init --recursive
            export PATH=$PATH:$HOME/.local/bin
            pip install -U coverage mock

      - run:
          name: run tests
          command: |
            coverage run --source=signac_dashboard/ -m unittest discover tests/
            coverage report -i --include="signac*"

      - store_artifacts:
          path: test-reports
          destination: test-reports

  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5-jessie

  test-3.4:
    <<: *test-template
    docker:
      - image: circleci/python:3.4-jessie

  test-pypy-3:
    <<: *test-template
    docker:
      - image: pypy:3

workflows:
  version: 2
  style-check-and-tests:
    jobs:
      - style-check
      - test-3.4:
          requires:
            - style-check
      - test-3.5:
          requires:
            - style-check
      - test-3.7:
          requires:
            - style-check
      - test-pypy-3:
          requires:
            - test-3.7
